usv_mqtt_bridge_node:
  ros__parameters:
    product_id: "M10"
    device_id: "USV_N0001"

    broker.host: "120.27.206.164"
    broker.port: 1883
    broker.client_id: "usv-mqtt-usv-n0001"
    broker.username: ""
    broker.password: ""
    broker.keepalive_sec: 15

    reconnect.initial_backoff_sec: 1.0
    reconnect.max_backoff_sec: 30.0

    publish_rates.status_hz: 2.0
    publish_rates.vision_targets_hz: 10.0
    publish_rates.radar_scan_hz: 10.0

    ros_topics.status_input_topic: "/usv/state"
    ros_topics.status_jetson_input_topic: "/usv/monitor/status_jetson/json"
    ros_topics.heartbeat_input_topic: "/usv/monitor/heartbeat/json"
    ros_topics.alarm_input_topic: ""
    ros_topics.diag_result_input_topic: ""
    ros_topics.radar_control_input_topic: ""
    ros_topics.radar_scan_input_topic: "/usv/radar/targets"
    ros_topics.radar_scan_config_input_topic: ""
    ros_topics.radar_map_input_topic: ""
    ros_topics.vision_targets_input_topic: "/usv/vision/metadata"
    ros_topics.perception_trajectory_input_topic: ""
    ros_topics.depth_input_topic: ""
    ros_topics.weather_input_topic: ""

    ros_topics.estop_output_topic: ""
    ros_topics.arm_output_topic: ""
    ros_topics.mode_output_topic: "/usv/cmd/mode/raw"
    ros_topics.auto_task_output_topic: ""
    ros_topics.radar_control_output_topic: "/usv/cmd/radar/control/raw"
    ros_topics.video_ctrl_output_topic: ""
    ros_topics.diag_request_output_topic: ""

    topics.status: "/sys/M10/USV_N0001/thing/property/status"
    topics.status_jetson: "/sys/M10/USV_N0001/thing/property/status_jetson"
    topics.heartbeat: "/sys/M10/USV_N0001/thing/event/heartbeat"
    topics.alarm: "/sys/M10/USV_N0001/thing/event/alarm"
    topics.diag_result: "/sys/M10/USV_N0001/thing/event/diag_result"
    topics.radar_control: "/sys/M10/USV_N0001/thing/service/radar_scan_config"
    topics.radar_scan: "/sys/M10/USV_N0001/thing/property/radar_scan"
    topics.radar_scan_config: "/sys/M10/USV_N0001/thing/event/radar_scan_config_reply"
    topics.radar_map: "/sys/M10/USV_N0001/thing/property/radar_map"
    topics.vision_targets: "/sys/M10/USV_N0001/thing/event/vision_targets"
    topics.perception_trajectory: "/sys/M10/USV_N0001/thing/property/perception_trajectory"
    topics.depth: "/sys/M10/USV_N0001/thing/property/depth"
    topics.weather: "/sys/M10/USV_N0001/thing/property/weather"

    topics.estop: "/sys/M10/USV_N0001/thing/service/estop"
    topics.arm: "/sys/M10/USV_N0001/thing/service/arm"
    topics.mode: "/sys/M10/USV_N0001/thing/service/mode"
    topics.auto_task: "/sys/M10/USV_N0001/thing/service/auto_task"
    topics.video_ctrl: "/sys/M10/USV_N0001/thing/service/video_ctrl"
    topics.diag_request: "/sys/M10/USV_N0001/thing/service/diag_request"
